# Generated by Django 4.2.6 on 2023-10-09 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='materials_provided',
            new_name='materials',
        ),
    ]
